[versions]
android-tools = "31.5.1"

[libraries]
com-android-tools-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "android-tools" }
com-android-tools-common = { module = "com.android.tools:common", version.ref = "android-tools" }
com-android-tools-annotations = { module = "com.android.tools:annotations", version.ref = "android-tools" }
com-android-tools-testutils = { module = "com.android.tools:testutils", version.ref = "android-tools" }
junit = "junit:junit:4.13.2"

[plugins]
download = { id = "de.undercouch.download", version = "5.0.4" }